### ISSUE TITLE
Please add bilinear upscaling in the absence of opengl shaders.

### ISSUE THREAD

**Issue by yamspy** [Northfear/OpenXcom-vita#1]
Due to the lack of OpenGL shaders and the use of nearest neighbor upscaling there are some image distortions, particularly noticeable in the inventory and map screens.

**Comment by Northfear** [comment]
Sounds good to me. I might add an option for it in the config file.
But I would actually recommend using 480x272 resolution with Display Mode set to "Fullscreen" and Geoscape Scale/Battlescape Scale set to "Full Display" for sharp looking image with x2 scaling.

**Comment by yamspy** [comment]
I decided to take a few screenshots to illlustrate what I meant, for some reason FMVs and the battlescape and map screens
 appear especially distorted, the rest of the game itself does not scale this poorly, I am not sure if those screens are scaled differently or what might be the cause of this.
![screen000](https://user-images.githubusercontent.com/73966961/120922423-f9afca80-c6c0-11eb-951d-1c64026e6296.jpg)
![screen001](https://user-images.githubusercontent.com/73966961/120922424-fae0f780-c6c0-11eb-9696-3beb05c3f3bb.jpg)
![screen000](https://user-images.githubusercontent.com/73966961/120922425-fb798e00-c6c0-11eb-8a87-073f38ff8b31.png)
![screen001](https://user-images.githubusercontent.com/73966961/120922426-fb798e00-c6c0-11eb-9695-6f062ea05de0.png)
(top 2 are vita, bottom 2 are pc)

**Comment by Northfear** [comment]
I think I know what's the problem here.
Use "Battlescape Scale" : "Full Display" with 480x272 resolution and "Original" with 320x200
320x200 with "Original" looks pretty good even w/o any filtering, so it's either resolution or scale setting that's wrong.

**Comment by yamspy** [comment]
The vita screenshots above were taken at 480x272 with "Full Display" selected, however I now tested 320x200 in "Original" and the map and inventory screens do appear less distorted now while the rest of the game only looks marginally worse, it's specifically the map and inventory screens that look this bad, the rest of the game during combat and in menus looks quite nice at 480x272 in "Full Display".

**Comment by Northfear** [comment]
Still sounds wrong to me. Here's an example of how things look in my case and a screenshot of my video settings.
![2021-06-07-111517](https://user-images.githubusercontent.com/11291116/120983074-0811eb00-c782-11eb-86ef-d488b2e28efa.png)
![2021-06-07-111458](https://user-images.githubusercontent.com/11291116/120983076-09431800-c782-11eb-9e7f-3bc0a3d4ede8.png)
![2021-06-07-111356](https://user-images.githubusercontent.com/11291116/120983079-09431800-c782-11eb-84f9-43b47016f06f.png)

**Comment by yamspy** [comment]
Nope, I tried again to set it to how it was and it still looks the same for me, I even rebooted without plugins to see if maybe that could be it, might our game files be different? (I am using v1.0-vita.2 with data files copied from a pc install of openxcom)

**Comment by Northfear** [comment]
> Nope, I tried again to set it to how it was and it still looks the same for me, I even rebooted without plugins to see if maybe that could be it, might our game files be different? (I am using v1.0-vita.2 with data files copied from a pc install of openxcom)

No idea honestly. What version are you using? I've tested everything with GoG release only

**Comment by yamspy** [comment]
I also used GOG release but patched the data files when prompted by the openxcom pc installer, I'm using a vita 2000 on 3.65, if that matters.

**Comment by Northfear** [comment]
@yamspy could you send me your whole ux0:data/OpenXcom folder somehow? Only one way to test it I guess..

**Comment by yamspy** [comment]
I think I discovered the cause of the problem, I deleted all my files and re-installed everything and initially the problem did not occur, however setting maximizeInfoScreens to true in the options.cfg or via the advanced options menu seems to be what causes this. This odd scaling also seems to happen on the pc version when using 480x272 (though there it can be alleviated by display filters) but not when using 960x544. I am not sure if this could be fixed on the vita port or is now an upstream issue.

**Comment by Northfear** [comment]
Glad that you've figured it out. I've added bilinear filtering in the latest update too (in Display Filter dropdown), so I'm closing this one.

**Comment by yamspy** [comment]
I tried bilinear filtering and for some reason these screens are still distorted at 480x272 full display, but now I can run the whole game at 320x200 without uneven pixels, thanks.

**Comment by Northfear** [comment]
> I tried bilinear filtering and for some reason these screens are still distorted at 480x272 full display, but now I can run the whole game at 320x200 without uneven pixels, thanks.

Probably due to some sort of ingame software scaling. Not much that I can do here unfortunately.
